kind: pipeline
type: kubernetes
name: consul-build

steps:
- name: build consul binary
  # use the same image specified in .circleci/config.yml
  image: golang:1.16.7
  commands:
    - wget https://github.com/codacy/codacy-gosec/releases/download/0.3.7/codacy-gosec-0.3.7
    - chmod +x codacy-gosec-0.3.7
    - curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s v2.9.3
    - gosec -fmt json -log log.txt ./... | ./codacy-gosec-0.3.7 
    - ./build-support/scripts/build-local.sh -o linux -a amd64
    - cp bin/consul .
  environment:
    EMAIL: devops@machinify.com
    GIT_AUTHOR_NAME: machinify
    GIT_COMMITTER_NAME: machinify
    BASH_ENV: .circleci/bash_env.sh
- name: build consul docker image
  image: plugins/ecr
  settings:
    repo: 677637302876.dkr.ecr.us-east-1.amazonaws.com/consul
    cache_from: 677637302876.dkr.ecr.us-east-1.amazonaws.com/consul:1.10.3-ingress-websocket-fix-latest
    build_args:
      - CONSUL_IMAGE_VERSION=1.10.3
    dockerfile: build-support/docker/Consul-Dev.dockerfile
    tags:
      - 1.10.3-ingress-websocket-fix-mfy${DRONE_BUILD_NUMBER}
    access_key:
      from_secret: ecr_accesskey
    secret_key:
      from_secret: ecr_secretkey
  depends_on:
    - build consul binary

- name: build consul zip
  image: 677637302876.dkr.ecr.us-east-1.amazonaws.com/k8s-build:pull-520-c39cdd0
  pull: always
  commands:
    - cd bin/
    - zip -r consul_1.10.3_linux_amd64_websocketfix.zip .
    - aws s3 --region us-east-1 cp consul_1.10.3_linux_amd64_websocketfix.zip s3://machinifydeploy/shared/latest/downloads/consul_1.10.3_linux_amd64_websocketfix.zip
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: klip_aws_accesskey
    AWS_SECRET_ACCESS_KEY:
      from_secret: klip_aws_secretkey
  depends_on:
    - build consul binary

trigger:
  branch:
  - ingress-websocket-fix
  event:
  - push
